export const RUNNER = 'RUNNER';
export const COMBINED_RUNNER = 'COMBINED_RUNNER';
export const SCOPED_RUNNER = 'SCOPED_RUNNER';
export const COMPONENT_RUNNER = 'COMPONENT_RUNNER';
export const AUTO_COMBINED_RUNNER = 'AUTO_COMBINED_RUNNER';
export const ROOT_RUNNER = 'ROOT_RUNNER';
export const WORKER_RUNNER = 'WORKER_RUNNER';
export const ERROR_RUNNER = 'ERROR_RUNNER';
